database:
    url: jdbc:mysql://localhost:3306/admission_contest_database?autoReconnect=true&useSSL=false
    port: 3306
    user: java_user
    pass: abcd1234

domain:
    Candidate:
        file: ./../resources/files_cnadidates_file.txt
        table: candidate
        separator: " | "
    Department:
        file: ./../resources/files_departments_file.txt
        table: department
        separator: " | "
    Option:
        file: ./../resources/files_option_file.txt
        table: option
        separator: " | "