CREATE TABLE `option` (
  id INT(6) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  candidate_id INT(6) UNSIGNED NOT NULL,
  department_id VARCHAR(20) NOT NULL,
  CONSTRAINT FK_OPTION_CANDIDATE FOREIGN KEY (candidate_id) REFERENCES candidate(id),
  CONSTRAINT FK_OPTION_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department(id)
)