insert into department (id, name, number_of_seats) values ('LUZ-848-S', 'national', 39);
insert into department (id, name, number_of_seats) values ('RBH-665-G', 'Expanded', 107);
insert into department (id, name, number_of_seats) values ('FMI-111-E', 'Multi-layered', 192);
insert into department (id, name, number_of_seats) values ('IDH-549-O', 'website', 59);
insert into department (id, name, number_of_seats) values ('SOH-178-X', 'Cross-platform', 119);
insert into department (id, name, number_of_seats) values ('ITK-641-V', 'mission-critical', 89);
insert into department (id, name, number_of_seats) values ('VZJ-443-P', 'interactive', 174);
insert into department (id, name, number_of_seats) values ('DLW-260-E', 'functionalities', 95);
insert into department (id, name, number_of_seats) values ('DJB-967-V', 'local area network', 87);
insert into department (id, name, number_of_seats) values ('UCM-486-K', 'incremental', 130);
insert into department (id, name, number_of_seats) values ('ALV-981-M', 'radical', 56);
insert into department (id, name, number_of_seats) values ('JFR-863-E', 'Ergonomic', 108);
insert into department (id, name, number_of_seats) values ('UNA-135-D', 'success', 100);
insert into department (id, name, number_of_seats) values ('OUE-213-O', 'info-mediaries', 45);
insert into department (id, name, number_of_seats) values ('JWE-132-Y', 'intangible', 15);
insert into department (id, name, number_of_seats) values ('LPM-981-U', 'full-range', 93);
insert into department (id, name, number_of_seats) values ('QNU-474-I', 'full-range', 74);
insert into department (id, name, number_of_seats) values ('IZL-848-U', 'user-facing', 105);
insert into department (id, name, number_of_seats) values ('IGF-654-X', 'Graphic Interface', 140);
insert into department (id, name, number_of_seats) values ('TLA-483-G', 'architecture', 189);
insert into department (id, name, number_of_seats) values ('AGW-571-E', 'Advanced', 24);
insert into department (id, name, number_of_seats) values ('DBG-755-A', 'Upgradable', 17);
insert into department (id, name, number_of_seats) values ('DIY-814-N', 'software', 58);
insert into department (id, name, number_of_seats) values ('FZV-801-F', 'Quality-focused', 180);
insert into department (id, name, number_of_seats) values ('XAV-545-S', 'Mandatory', 82);
insert into department (id, name, number_of_seats) values ('ESM-668-C', 'Implemented', 155);
insert into department (id, name, number_of_seats) values ('BXU-819-C', 'Open-source', 36);
insert into department (id, name, number_of_seats) values ('CFL-579-E', 'tertiary', 147);
insert into department (id, name, number_of_seats) values ('HZF-362-D', '5th generation', 102);
insert into department (id, name, number_of_seats) values ('UXA-670-U', 'middleware', 87);
insert into department (id, name, number_of_seats) values ('JMK-148-W', 'fresh-thinking', 52);
insert into department (id, name, number_of_seats) values ('XYH-967-L', 'hybrid', 173);
insert into department (id, name, number_of_seats) values ('ZTO-850-G', 'Cross-group', 43);
insert into department (id, name, number_of_seats) values ('VUF-144-A', 'stable', 107);
insert into department (id, name, number_of_seats) values ('TRJ-643-X', 'Proactive', 113);
insert into department (id, name, number_of_seats) values ('SKP-397-V', 'complexity', 22);
insert into department (id, name, number_of_seats) values ('MBX-986-E', 'open architecture', 25);
insert into department (id, name, number_of_seats) values ('OHL-849-U', 'zero administration', 113);
insert into department (id, name, number_of_seats) values ('TZG-689-H', 'Fundamental', 123);
insert into department (id, name, number_of_seats) values ('LIB-431-H', 'circuit', 96);
insert into department (id, name, number_of_seats) values ('XWH-196-G', 'matrix', 74);
insert into department (id, name, number_of_seats) values ('RDF-716-H', 'budgetary management', 144);
insert into department (id, name, number_of_seats) values ('SVU-857-C', 'hybrid', 127);
insert into department (id, name, number_of_seats) values ('BFN-261-M', 'content-based', 66);
insert into department (id, name, number_of_seats) values ('TZO-752-B', 'Face to face', 140);
insert into department (id, name, number_of_seats) values ('XQZ-550-A', 'definition', 184);
insert into department (id, name, number_of_seats) values ('ALX-057-J', 'Organic', 106);
insert into department (id, name, number_of_seats) values ('EGR-693-Z', 'intranet', 95);
insert into department (id, name, number_of_seats) values ('IVB-781-M', 'portal', 176);
insert into department (id, name, number_of_seats) values ('GAX-919-P', 'holistic', 40);
insert into department (id, name, number_of_seats) values ('TOY-723-T', 'optimizing', 107);
insert into department (id, name, number_of_seats) values ('XMK-904-L', 'responsive', 104);
insert into department (id, name, number_of_seats) values ('DJC-526-I', 'strategy', 52);
insert into department (id, name, number_of_seats) values ('XWZ-294-N', 'Expanded', 146);
insert into department (id, name, number_of_seats) values ('LEJ-274-G', 'leading edge', 142);
insert into department (id, name, number_of_seats) values ('XHU-740-C', 'empowering', 55);
insert into department (id, name, number_of_seats) values ('FEG-366-K', 'solution-oriented', 150);
insert into department (id, name, number_of_seats) values ('BJC-214-D', 'application', 43);
insert into department (id, name, number_of_seats) values ('THQ-234-N', 'collaboration', 182);
insert into department (id, name, number_of_seats) values ('GYH-665-P', 'explicit', 63);
insert into department (id, name, number_of_seats) values ('EZI-566-O', 'mission-critical', 107);
insert into department (id, name, number_of_seats) values ('WBA-697-U', 'Profound', 168);
insert into department (id, name, number_of_seats) values ('YDX-108-N', 'Visionary', 91);
insert into department (id, name, number_of_seats) values ('QZG-298-H', 'emulation', 131);
insert into department (id, name, number_of_seats) values ('MIX-680-E', 'responsive', 190);
insert into department (id, name, number_of_seats) values ('JRO-269-T', 'discrete', 129);
insert into department (id, name, number_of_seats) values ('DVK-601-A', 'application', 198);
insert into department (id, name, number_of_seats) values ('GLB-018-F', 'dynamic', 107);
insert into department (id, name, number_of_seats) values ('NOE-279-N', 'task-force', 83);
insert into department (id, name, number_of_seats) values ('TYN-386-Q', 'real-time', 26);
insert into department (id, name, number_of_seats) values ('DWJ-020-M', 'encoding', 175);
insert into department (id, name, number_of_seats) values ('YPX-927-T', 'collaboration', 17);
insert into department (id, name, number_of_seats) values ('PUD-591-H', 'Graphical User Interface', 162);
insert into department (id, name, number_of_seats) values ('KEA-119-A', 'forecast', 127);
insert into department (id, name, number_of_seats) values ('FKP-184-O', 'client-driven', 157);
insert into department (id, name, number_of_seats) values ('PHO-353-I', 'system engine', 40);
insert into department (id, name, number_of_seats) values ('KLQ-851-N', 'Centralized', 54);
insert into department (id, name, number_of_seats) values ('RHN-793-C', 'Up-sized', 106);
insert into department (id, name, number_of_seats) values ('HFG-992-F', 'emulation', 174);
insert into department (id, name, number_of_seats) values ('BCJ-617-V', 'global', 87);
insert into department (id, name, number_of_seats) values ('VBR-478-P', 'multimedia', 31);
insert into department (id, name, number_of_seats) values ('XGV-245-B', 'secondary', 34);
insert into department (id, name, number_of_seats) values ('TNE-398-F', 'success', 171);
insert into department (id, name, number_of_seats) values ('ZID-744-S', 'analyzer', 113);
insert into department (id, name, number_of_seats) values ('IWK-567-R', 'Up-sized', 158);
insert into department (id, name, number_of_seats) values ('XAH-528-I', 'Reverse-engineered', 10);
insert into department (id, name, number_of_seats) values ('HRT-185-J', 'Centralized', 144);
insert into department (id, name, number_of_seats) values ('VBW-241-I', 'access', 196);
insert into department (id, name, number_of_seats) values ('IOD-354-S', 'Integrated', 100);
insert into department (id, name, number_of_seats) values ('QWF-023-K', 'help-desk', 117);
insert into department (id, name, number_of_seats) values ('WMA-713-U', 'knowledge user', 60);
insert into department (id, name, number_of_seats) values ('ASZ-442-Q', 'flexibility', 194);
insert into department (id, name, number_of_seats) values ('HJB-891-Y', 'matrix', 120);
insert into department (id, name, number_of_seats) values ('JWU-049-L', 'knowledge user', 33);
insert into department (id, name, number_of_seats) values ('TKS-377-Q', 'installation', 90);
insert into department (id, name, number_of_seats) values ('MXI-365-W', 'zero administration', 163);
insert into department (id, name, number_of_seats) values ('PMC-354-W', 'collaboration', 143);
insert into department (id, name, number_of_seats) values ('LWB-845-S', 'definition', 184);
insert into department (id, name, number_of_seats) values ('HVI-782-Y', 'Customer-focused', 29);
insert into department (id, name, number_of_seats) values ('PQW-669-N', 'executive', 186);
insert into department (id, name, number_of_seats) values ('DHM-667-P', 'Synergistic', 129);
insert into department (id, name, number_of_seats) values ('DSN-170-Z', 'Progressive', 116);
insert into department (id, name, number_of_seats) values ('WPS-979-N', 'bottom-line', 76);
insert into department (id, name, number_of_seats) values ('IFZ-133-C', 'Cross-group', 171);
insert into department (id, name, number_of_seats) values ('ALN-145-D', 'Re-contextualized', 89);
insert into department (id, name, number_of_seats) values ('DEP-379-L', 'Graphical User Interface', 44);
insert into department (id, name, number_of_seats) values ('DLM-997-J', 'Robust', 173);
insert into department (id, name, number_of_seats) values ('ERU-542-C', 'challenge', 98);
insert into department (id, name, number_of_seats) values ('YLE-426-D', 'data-warehouse', 117);
insert into department (id, name, number_of_seats) values ('ARO-901-P', 'optimizing', 16);
insert into department (id, name, number_of_seats) values ('FDC-342-D', 'holistic', 119);
insert into department (id, name, number_of_seats) values ('QKH-521-A', 'bottom-line', 28);
insert into department (id, name, number_of_seats) values ('GRL-543-Z', 'infrastructure', 13);
insert into department (id, name, number_of_seats) values ('DCH-441-B', 'hardware', 60);
insert into department (id, name, number_of_seats) values ('CIW-239-B', 'Front-line', 13);
insert into department (id, name, number_of_seats) values ('NWE-532-O', 'Integrated', 67);
insert into department (id, name, number_of_seats) values ('FHE-533-G', 'Vision-oriented', 158);
insert into department (id, name, number_of_seats) values ('ROG-650-B', 'Down-sized', 101);
insert into department (id, name, number_of_seats) values ('MSE-761-Q', 'Innovative', 197);
insert into department (id, name, number_of_seats) values ('BOK-499-X', 'groupware', 127);
insert into department (id, name, number_of_seats) values ('LGR-513-N', 'Synchronised', 168);
insert into department (id, name, number_of_seats) values ('NSH-760-A', 'capability', 28);
insert into department (id, name, number_of_seats) values ('UGH-137-L', 'national', 66);
insert into department (id, name, number_of_seats) values ('UMH-139-C', 'exuding', 159);
insert into department (id, name, number_of_seats) values ('KWB-167-M', 'flexibility', 122);
insert into department (id, name, number_of_seats) values ('REU-839-K', 'moratorium', 149);
insert into department (id, name, number_of_seats) values ('VXK-184-P', 'stable', 106);
insert into department (id, name, number_of_seats) values ('QAD-497-N', 'Multi-layered', 40);
insert into department (id, name, number_of_seats) values ('FLH-547-J', 'Assimilated', 87);
insert into department (id, name, number_of_seats) values ('RSB-387-Z', 'non-volatile', 156);
insert into department (id, name, number_of_seats) values ('ZRJ-505-C', 'paradigm', 111);
insert into department (id, name, number_of_seats) values ('WQZ-461-S', 'bottom-line', 81);
insert into department (id, name, number_of_seats) values ('ILV-588-R', 'static', 14);
insert into department (id, name, number_of_seats) values ('MCR-056-A', 'attitude', 14);
insert into department (id, name, number_of_seats) values ('YNW-450-A', 'middleware', 102);
insert into department (id, name, number_of_seats) values ('HAM-637-K', 'Ameliorated', 43);
insert into department (id, name, number_of_seats) values ('ZJN-069-W', 'Enterprise-wide', 42);
insert into department (id, name, number_of_seats) values ('EDS-929-D', 'regional', 42);
insert into department (id, name, number_of_seats) values ('CKX-644-R', 'budgetary management', 149);
insert into department (id, name, number_of_seats) values ('ARV-110-Y', 'interactive', 59);
insert into department (id, name, number_of_seats) values ('FAI-079-A', 'Visionary', 29);
insert into department (id, name, number_of_seats) values ('DHZ-984-A', 'Open-architected', 95);
insert into department (id, name, number_of_seats) values ('UJI-693-I', 'Progressive', 154);
insert into department (id, name, number_of_seats) values ('WNO-872-C', 'ability', 53);
insert into department (id, name, number_of_seats) values ('MXH-759-F', 'full-range', 194);
insert into department (id, name, number_of_seats) values ('MTE-396-Y', 'regional', 156);
insert into department (id, name, number_of_seats) values ('KRU-462-S', 'orchestration', 19);
insert into department (id, name, number_of_seats) values ('ZYX-745-V', 'intranet', 168);
insert into department (id, name, number_of_seats) values ('HMD-396-W', 'flexibility', 61);
insert into department (id, name, number_of_seats) values ('XJM-044-Q', 'functionalities', 75);
insert into department (id, name, number_of_seats) values ('TIN-823-J', 'Cross-group', 159);
insert into department (id, name, number_of_seats) values ('POC-989-C', 'Public-key', 182);
insert into department (id, name, number_of_seats) values ('YRP-106-Y', 'projection', 174);
insert into department (id, name, number_of_seats) values ('LPW-732-A', 'instruction set', 51);
insert into department (id, name, number_of_seats) values ('FBT-113-G', 'archive', 112);
insert into department (id, name, number_of_seats) values ('WLQ-909-Y', 'Re-engineered', 148);
insert into department (id, name, number_of_seats) values ('HUY-271-D', 'Advanced', 107);
insert into department (id, name, number_of_seats) values ('FPL-448-R', 'Synchronised', 191);
insert into department (id, name, number_of_seats) values ('HDB-268-O', 'Switchable', 58);
insert into department (id, name, number_of_seats) values ('YTJ-117-F', 'client-server', 129);
insert into department (id, name, number_of_seats) values ('AML-845-F', 'definition', 123);
insert into department (id, name, number_of_seats) values ('TXP-254-L', 'Synergistic', 140);
insert into department (id, name, number_of_seats) values ('ILD-369-S', 'emulation', 94);
insert into department (id, name, number_of_seats) values ('JXH-136-N', 'Integrated', 60);
insert into department (id, name, number_of_seats) values ('DCX-217-U', 'Reduced', 153);
insert into department (id, name, number_of_seats) values ('LNE-133-L', 'coherent', 30);
insert into department (id, name, number_of_seats) values ('KIE-674-B', 'solution-oriented', 21);
insert into department (id, name, number_of_seats) values ('VHD-691-Q', 'migration', 17);
insert into department (id, name, number_of_seats) values ('JTZ-443-S', 'Reverse-engineered', 198);
insert into department (id, name, number_of_seats) values ('ZAL-772-H', 'impactful', 181);
insert into department (id, name, number_of_seats) values ('SRW-033-E', 'Seamless', 77);
insert into department (id, name, number_of_seats) values ('ACU-854-C', 'system-worthy', 56);
insert into department (id, name, number_of_seats) values ('UEO-036-A', 'archive', 150);
insert into department (id, name, number_of_seats) values ('JMT-063-F', '5th generation', 177);
insert into department (id, name, number_of_seats) values ('OSU-784-Y', 'core', 130);
insert into department (id, name, number_of_seats) values ('OWX-221-A', 'national', 13);
insert into department (id, name, number_of_seats) values ('TLI-021-N', 'benchmark', 112);
insert into department (id, name, number_of_seats) values ('ONQ-286-Y', 'tertiary', 195);
insert into department (id, name, number_of_seats) values ('NEI-061-P', 'disintermediate', 183);
insert into department (id, name, number_of_seats) values ('UYP-174-L', '3rd generation', 35);
insert into department (id, name, number_of_seats) values ('ABS-784-Q', 'Visionary', 69);
insert into department (id, name, number_of_seats) values ('SMR-974-Q', 'installation', 16);
insert into department (id, name, number_of_seats) values ('GTH-053-H', 'Grass-roots', 50);
insert into department (id, name, number_of_seats) values ('TVS-232-W', 'Progressive', 179);
insert into department (id, name, number_of_seats) values ('UHT-979-R', 'product', 70);
insert into department (id, name, number_of_seats) values ('PGD-671-H', 'Versatile', 39);
insert into department (id, name, number_of_seats) values ('KPD-178-Y', 'De-engineered', 136);
insert into department (id, name, number_of_seats) values ('TQO-032-U', 'coherent', 141);
insert into department (id, name, number_of_seats) values ('GHT-318-O', 'Stand-alone', 162);
insert into department (id, name, number_of_seats) values ('JMI-569-C', 'parallelism', 40);
insert into department (id, name, number_of_seats) values ('WXQ-902-Q', 'Virtual', 47);
insert into department (id, name, number_of_seats) values ('EWB-990-O', 'paradigm', 124);
insert into department (id, name, number_of_seats) values ('JDU-531-X', 'Face to face', 106);
insert into department (id, name, number_of_seats) values ('XRO-362-D', 'global', 94);
insert into department (id, name, number_of_seats) values ('OCQ-039-S', 'definition', 62);
insert into department (id, name, number_of_seats) values ('YLG-413-O', 'Re-engineered', 147);
insert into department (id, name, number_of_seats) values ('WSV-954-Q', 'asynchronous', 88);
insert into department (id, name, number_of_seats) values ('QFJ-215-T', 'Exclusive', 179);
insert into department (id, name, number_of_seats) values ('JYA-057-U', 'neutral', 186);
insert into department (id, name, number_of_seats) values ('IUV-887-B', 'hardware', 93);
insert into department (id, name, number_of_seats) values ('WLS-519-S', 'process improvement', 25);
insert into department (id, name, number_of_seats) values ('FSR-588-I', '3rd generation', 94);
insert into department (id, name, number_of_seats) values ('ICW-351-A', 'bi-directional', 74);
insert into department (id, name, number_of_seats) values ('BLE-795-U', 'middleware', 82);
insert into department (id, name, number_of_seats) values ('RSO-356-W', 'concept', 200);
insert into department (id, name, number_of_seats) values ('OMS-988-M', 'Optional', 63);
insert into department (id, name, number_of_seats) values ('MDP-496-F', 'Managed', 28);
insert into department (id, name, number_of_seats) values ('XTS-313-B', 'utilisation', 146);
insert into department (id, name, number_of_seats) values ('FWU-253-H', '6th generation', 162);
insert into department (id, name, number_of_seats) values ('JPY-370-V', 'policy', 37);
insert into department (id, name, number_of_seats) values ('DYA-408-A', 'modular', 23);
insert into department (id, name, number_of_seats) values ('IGX-962-K', 'contingency', 77);
insert into department (id, name, number_of_seats) values ('YVC-398-Q', 'structure', 111);
insert into department (id, name, number_of_seats) values ('MUF-881-F', 'web-enabled', 45);
insert into department (id, name, number_of_seats) values ('DGE-315-J', 'Proactive', 161);
insert into department (id, name, number_of_seats) values ('ZAY-276-G', 'Reduced', 66);
insert into department (id, name, number_of_seats) values ('CWM-171-G', 'database', 129);
insert into department (id, name, number_of_seats) values ('HOD-969-F', 'access', 167);
insert into department (id, name, number_of_seats) values ('WEQ-043-P', 'neural-net', 86);
insert into department (id, name, number_of_seats) values ('FNB-887-Z', 'Business-focused', 109);
insert into department (id, name, number_of_seats) values ('PJB-835-Z', 'radical', 112);
insert into department (id, name, number_of_seats) values ('TPU-213-H', 'attitude', 23);
insert into department (id, name, number_of_seats) values ('EZP-439-F', 'Reactive', 28);
insert into department (id, name, number_of_seats) values ('SXG-064-Q', 'mobile', 62);
insert into department (id, name, number_of_seats) values ('ILD-352-L', 'Grass-roots', 116);
insert into department (id, name, number_of_seats) values ('PBR-145-A', 'systematic', 185);
insert into department (id, name, number_of_seats) values ('IRE-389-N', 'Secured', 153);
insert into department (id, name, number_of_seats) values ('TGC-120-U', 'object-oriented', 117);
insert into department (id, name, number_of_seats) values ('EKT-145-V', 'exuding', 48);
insert into department (id, name, number_of_seats) values ('LCT-465-J', 'Phased', 93);
insert into department (id, name, number_of_seats) values ('QSX-664-V', 'Synergized', 47);
insert into department (id, name, number_of_seats) values ('BJL-160-U', 'global', 42);
insert into department (id, name, number_of_seats) values ('YRS-083-H', 'access', 118);
insert into department (id, name, number_of_seats) values ('BHO-095-H', 'Operative', 138);
insert into department (id, name, number_of_seats) values ('EXT-510-C', 'Triple-buffered', 143);
insert into department (id, name, number_of_seats) values ('ZKX-185-C', 'Multi-channelled', 146);
insert into department (id, name, number_of_seats) values ('OEL-567-D', 'Universal', 104);
insert into department (id, name, number_of_seats) values ('LFS-580-L', 'multi-tasking', 73);
insert into department (id, name, number_of_seats) values ('OXJ-915-Q', 'Stand-alone', 37);
insert into department (id, name, number_of_seats) values ('HTF-316-Y', 'approach', 103);
insert into department (id, name, number_of_seats) values ('ATC-881-U', 'functionalities', 169);
insert into department (id, name, number_of_seats) values ('RBO-251-M', 'clear-thinking', 98);
insert into department (id, name, number_of_seats) values ('EKG-551-Q', 'context-sensitive', 109);
insert into department (id, name, number_of_seats) values ('XJC-893-D', 'Cross-group', 121);
insert into department (id, name, number_of_seats) values ('VBJ-391-Y', 'local area network', 180);
insert into department (id, name, number_of_seats) values ('VOD-334-Q', 'throughput', 151);
insert into department (id, name, number_of_seats) values ('JPE-230-G', 'framework', 173);
insert into department (id, name, number_of_seats) values ('RTP-212-P', 'attitude', 86);
insert into department (id, name, number_of_seats) values ('ESD-280-E', 'Networked', 47);
insert into department (id, name, number_of_seats) values ('VWQ-332-Y', 'even-keeled', 79);
insert into department (id, name, number_of_seats) values ('BTO-203-F', 'Balanced', 50);
insert into department (id, name, number_of_seats) values ('YNQ-624-W', 'artificial intelligence', 83);
insert into department (id, name, number_of_seats) values ('NAG-155-P', '6th generation', 71);
insert into department (id, name, number_of_seats) values ('UQN-800-R', 'Configurable', 57);
insert into department (id, name, number_of_seats) values ('KVX-492-C', 'Implemented', 78);
insert into department (id, name, number_of_seats) values ('GWN-787-N', 'Progressive', 56);
insert into department (id, name, number_of_seats) values ('NZT-977-N', 'Universal', 194);
insert into department (id, name, number_of_seats) values ('FCM-960-U', 'Operative', 94);
insert into department (id, name, number_of_seats) values ('IYS-591-R', 'structure', 168);
insert into department (id, name, number_of_seats) values ('AWY-382-Z', 'bi-directional', 158);
insert into department (id, name, number_of_seats) values ('TAH-958-O', 'actuating', 67);
insert into department (id, name, number_of_seats) values ('YHW-228-Q', 'instruction set', 123);
insert into department (id, name, number_of_seats) values ('PMB-215-J', 'ability', 20);
insert into department (id, name, number_of_seats) values ('ZNV-136-B', 'Cross-platform', 200);
insert into department (id, name, number_of_seats) values ('FWK-086-S', 'maximized', 94);
insert into department (id, name, number_of_seats) values ('IFX-848-U', 'conglomeration', 71);
insert into department (id, name, number_of_seats) values ('WUO-638-J', 'Implemented', 59);
insert into department (id, name, number_of_seats) values ('BYR-686-H', 'analyzing', 189);
insert into department (id, name, number_of_seats) values ('IUJ-761-U', 'didactic', 143);
insert into department (id, name, number_of_seats) values ('QVU-383-C', 'mission-critical', 17);
insert into department (id, name, number_of_seats) values ('VFZ-316-U', 'Face to face', 14);
insert into department (id, name, number_of_seats) values ('YFH-612-N', 'Ergonomic', 114);
insert into department (id, name, number_of_seats) values ('YRU-217-D', 'scalable', 114);
insert into department (id, name, number_of_seats) values ('DKA-402-S', 'Virtual', 149);
insert into department (id, name, number_of_seats) values ('DLC-228-T', 'matrix', 13);
insert into department (id, name, number_of_seats) values ('FPO-738-J', 'customer loyalty', 16);
insert into department (id, name, number_of_seats) values ('FNT-533-D', 'executive', 163);
insert into department (id, name, number_of_seats) values ('CSW-646-M', 'pricing structure', 200);
insert into department (id, name, number_of_seats) values ('ATP-383-H', 'Advanced', 122);
insert into department (id, name, number_of_seats) values ('BKN-602-A', '4th generation', 197);
insert into department (id, name, number_of_seats) values ('UTS-110-D', 'knowledge user', 104);
insert into department (id, name, number_of_seats) values ('CGS-467-Z', 'client-server', 100);
insert into department (id, name, number_of_seats) values ('EUF-550-S', 'access', 193);
insert into department (id, name, number_of_seats) values ('UZD-033-Y', 'Multi-layered', 149);
insert into department (id, name, number_of_seats) values ('DJO-006-E', 'function', 80);
insert into department (id, name, number_of_seats) values ('SOP-356-B', 'collaboration', 16);
insert into department (id, name, number_of_seats) values ('NOD-668-D', 'Seamless', 82);
insert into department (id, name, number_of_seats) values ('JUR-845-G', 'solution', 193);
insert into department (id, name, number_of_seats) values ('BGH-152-Z', 'task-force', 77);
insert into department (id, name, number_of_seats) values ('ETU-621-U', 'system engine', 73);
insert into department (id, name, number_of_seats) values ('XAW-857-Z', 'Re-engineered', 61);
insert into department (id, name, number_of_seats) values ('GUB-382-Y', 'time-frame', 147);
insert into department (id, name, number_of_seats) values ('SAR-598-C', 'Cross-platform', 197);
insert into department (id, name, number_of_seats) values ('HSG-181-I', 'protocol', 91);
insert into department (id, name, number_of_seats) values ('OLV-190-X', 'intermediate', 149);
insert into department (id, name, number_of_seats) values ('VKJ-731-K', 'throughput', 47);
insert into department (id, name, number_of_seats) values ('UHV-224-C', 'Open-source', 110);
insert into department (id, name, number_of_seats) values ('JFH-014-C', 'Organized', 12);
insert into department (id, name, number_of_seats) values ('JWN-190-T', 'function', 179);
insert into department (id, name, number_of_seats) values ('DFG-056-W', 'software', 185);
insert into department (id, name, number_of_seats) values ('GCN-188-S', 'Configurable', 50);
insert into department (id, name, number_of_seats) values ('CMW-158-W', 'moratorium', 74);
insert into department (id, name, number_of_seats) values ('YGN-626-C', 'optimizing', 122);
insert into department (id, name, number_of_seats) values ('DFQ-847-C', 'algorithm', 61);
insert into department (id, name, number_of_seats) values ('MSC-354-X', 'concept', 66);
insert into department (id, name, number_of_seats) values ('BMZ-749-M', 'Networked', 175);
insert into department (id, name, number_of_seats) values ('TJG-673-Y', 'logistical', 68);
insert into department (id, name, number_of_seats) values ('RKL-490-D', 'firmware', 88);
insert into department (id, name, number_of_seats) values ('JAQ-447-R', 'solution-oriented', 150);
insert into department (id, name, number_of_seats) values ('YUX-811-A', 'fresh-thinking', 57);
insert into department (id, name, number_of_seats) values ('ATP-392-X', 'concept', 200);
insert into department (id, name, number_of_seats) values ('RFI-311-K', 'pricing structure', 71);
insert into department (id, name, number_of_seats) values ('TFW-869-Q', 'concept', 30);
insert into department (id, name, number_of_seats) values ('OIV-453-L', 'full-range', 131);
insert into department (id, name, number_of_seats) values ('BVS-923-W', 'Reverse-engineered', 193);
insert into department (id, name, number_of_seats) values ('MEC-319-M', 'extranet', 154);
insert into department (id, name, number_of_seats) values ('IBG-607-F', 'project', 114);
insert into department (id, name, number_of_seats) values ('QOX-434-J', 'motivating', 97);
insert into department (id, name, number_of_seats) values ('CRO-150-O', 'bi-directional', 82);
insert into department (id, name, number_of_seats) values ('LTW-840-Q', 'moratorium', 109);
insert into department (id, name, number_of_seats) values ('ECO-451-X', 'next generation', 44);
insert into department (id, name, number_of_seats) values ('OAB-938-Y', 'Stand-alone', 164);
insert into department (id, name, number_of_seats) values ('PTG-120-E', 'Profit-focused', 191);
insert into department (id, name, number_of_seats) values ('POY-327-F', 'real-time', 146);
insert into department (id, name, number_of_seats) values ('MOC-593-S', 'solution-oriented', 126);
insert into department (id, name, number_of_seats) values ('DTA-241-P', 'Organic', 148);
insert into department (id, name, number_of_seats) values ('TSX-279-M', 'Digitized', 77);
insert into department (id, name, number_of_seats) values ('EBX-789-U', 'intangible', 200);
insert into department (id, name, number_of_seats) values ('BZN-077-Y', 'capacity', 119);
insert into department (id, name, number_of_seats) values ('SNV-312-W', 'artificial intelligence', 108);
insert into department (id, name, number_of_seats) values ('RIM-980-B', 'radical', 35);
insert into department (id, name, number_of_seats) values ('SFN-653-M', 'Implemented', 65);
insert into department (id, name, number_of_seats) values ('GTI-004-W', 'object-oriented', 185);
insert into department (id, name, number_of_seats) values ('BTS-800-N', 'service-desk', 64);
insert into department (id, name, number_of_seats) values ('IPC-322-P', 'Optimized', 38);
insert into department (id, name, number_of_seats) values ('EDU-567-U', 'access', 78);
insert into department (id, name, number_of_seats) values ('EHU-087-N', '24 hour', 172);
insert into department (id, name, number_of_seats) values ('AZG-695-V', 'Graphical User Interface', 85);
insert into department (id, name, number_of_seats) values ('HUB-137-C', 'Cross-group', 55);
insert into department (id, name, number_of_seats) values ('GVS-616-T', '5th generation', 79);
insert into department (id, name, number_of_seats) values ('HCZ-709-L', 'User-friendly', 106);
insert into department (id, name, number_of_seats) values ('FJS-681-N', 'Synergized', 137);
insert into department (id, name, number_of_seats) values ('HJX-959-F', 'interface', 157);
insert into department (id, name, number_of_seats) values ('RVC-916-G', 'zero tolerance', 27);
insert into department (id, name, number_of_seats) values ('SVT-899-X', 'upward-trending', 191);
insert into department (id, name, number_of_seats) values ('TUL-415-J', 'migration', 46);
insert into department (id, name, number_of_seats) values ('EDJ-449-A', 'fault-tolerant', 127);
insert into department (id, name, number_of_seats) values ('YHL-974-B', 'didactic', 122);
insert into department (id, name, number_of_seats) values ('KFH-043-E', 'reciprocal', 183);
insert into department (id, name, number_of_seats) values ('MEG-652-X', 'motivating', 16);
insert into department (id, name, number_of_seats) values ('MPR-947-J', 'Polarised', 10);
insert into department (id, name, number_of_seats) values ('LFJ-016-H', 'foreground', 77);
insert into department (id, name, number_of_seats) values ('KEB-988-B', 'well-modulated', 164);
insert into department (id, name, number_of_seats) values ('XON-341-M', 'Face to face', 189);
insert into department (id, name, number_of_seats) values ('JIV-826-X', 'dynamic', 172);
insert into department (id, name, number_of_seats) values ('FJX-760-F', 'heuristic', 134);
insert into department (id, name, number_of_seats) values ('VMC-802-M', 'open system', 142);
insert into department (id, name, number_of_seats) values ('LPH-293-I', '4th generation', 68);
insert into department (id, name, number_of_seats) values ('ZTF-386-E', 'collaboration', 145);
insert into department (id, name, number_of_seats) values ('TFD-378-K', 'Horizontal', 20);
insert into department (id, name, number_of_seats) values ('WKN-569-A', 'portal', 49);
insert into department (id, name, number_of_seats) values ('OVF-383-G', 'encoding', 179);
insert into department (id, name, number_of_seats) values ('UOI-510-P', 'emulation', 150);
insert into department (id, name, number_of_seats) values ('ZAF-583-Y', 'responsive', 120);
insert into department (id, name, number_of_seats) values ('OGH-148-G', 'well-modulated', 163);
insert into department (id, name, number_of_seats) values ('ERS-627-P', 'discrete', 85);
insert into department (id, name, number_of_seats) values ('LMK-066-M', 'Secured', 46);
insert into department (id, name, number_of_seats) values ('WIG-971-O', 'Organized', 151);
insert into department (id, name, number_of_seats) values ('UFQ-839-Z', 'scalable', 137);
insert into department (id, name, number_of_seats) values ('OYC-713-K', 'success', 13);
insert into department (id, name, number_of_seats) values ('ARY-106-E', 'Object-based', 25);
insert into department (id, name, number_of_seats) values ('GMV-865-W', 'content-based', 97);
insert into department (id, name, number_of_seats) values ('FTI-814-L', 'Networked', 77);
insert into department (id, name, number_of_seats) values ('BPN-253-P', 'coherent', 142);
insert into department (id, name, number_of_seats) values ('QED-050-U', 'Graphical User Interface', 157);
insert into department (id, name, number_of_seats) values ('SRK-805-B', 'data-warehouse', 90);
insert into department (id, name, number_of_seats) values ('QPM-589-A', 'policy', 166);
insert into department (id, name, number_of_seats) values ('NMR-843-H', 'protocol', 197);
insert into department (id, name, number_of_seats) values ('PMB-741-B', 'Focused', 50);
insert into department (id, name, number_of_seats) values ('OME-037-H', 'leverage', 148);
insert into department (id, name, number_of_seats) values ('FGI-582-U', 'model', 30);
insert into department (id, name, number_of_seats) values ('ISK-035-B', 'challenge', 140);
insert into department (id, name, number_of_seats) values ('WLA-653-R', 'Phased', 133);
insert into department (id, name, number_of_seats) values ('TZD-630-O', 'standardization', 194);
insert into department (id, name, number_of_seats) values ('TQO-517-F', 'zero defect', 117);
insert into department (id, name, number_of_seats) values ('RGW-842-T', 'emulation', 166);
insert into department (id, name, number_of_seats) values ('VTP-310-P', 'object-oriented', 12);
insert into department (id, name, number_of_seats) values ('BVX-948-S', 'intermediate', 92);
insert into department (id, name, number_of_seats) values ('BMH-389-X', 'core', 196);
insert into department (id, name, number_of_seats) values ('LZQ-934-V', 'Monitored', 56);
insert into department (id, name, number_of_seats) values ('DSF-028-B', 'Right-sized', 63);
insert into department (id, name, number_of_seats) values ('DXU-455-G', 'time-frame', 113);
insert into department (id, name, number_of_seats) values ('QRY-453-I', 'Mandatory', 63);
insert into department (id, name, number_of_seats) values ('LUD-840-Y', 'object-oriented', 148);
insert into department (id, name, number_of_seats) values ('NCS-695-S', 'Proactive', 121);
insert into department (id, name, number_of_seats) values ('WLR-209-A', 'algorithm', 125);
insert into department (id, name, number_of_seats) values ('ENM-825-J', 'asynchronous', 185);
insert into department (id, name, number_of_seats) values ('YIJ-316-Q', 'Reduced', 134);
insert into department (id, name, number_of_seats) values ('IOW-610-I', 'motivating', 189);
insert into department (id, name, number_of_seats) values ('JEO-363-Y', 'transitional', 168);
insert into department (id, name, number_of_seats) values ('GKX-219-Y', 'middleware', 182);
insert into department (id, name, number_of_seats) values ('XDM-796-C', 'orchestration', 79);
insert into department (id, name, number_of_seats) values ('JDI-182-M', 'attitude-oriented', 100);
insert into department (id, name, number_of_seats) values ('URE-584-L', 'Switchable', 172);
insert into department (id, name, number_of_seats) values ('FSK-968-K', 'instruction set', 73);
insert into department (id, name, number_of_seats) values ('KLO-794-G', 'conglomeration', 192);
insert into department (id, name, number_of_seats) values ('YME-710-B', 'Open-source', 185);
insert into department (id, name, number_of_seats) values ('BVH-678-U', 'process improvement', 92);
insert into department (id, name, number_of_seats) values ('HAT-794-W', 'Digitized', 52);
insert into department (id, name, number_of_seats) values ('ZBD-520-F', 'Public-key', 31);
insert into department (id, name, number_of_seats) values ('LPQ-279-L', 'attitude-oriented', 43);
insert into department (id, name, number_of_seats) values ('SNR-062-T', 'systematic', 86);
insert into department (id, name, number_of_seats) values ('TUA-488-X', 'multi-tasking', 161);
insert into department (id, name, number_of_seats) values ('JVL-295-S', 'static', 192);
insert into department (id, name, number_of_seats) values ('HTS-088-S', 'impactful', 60);
insert into department (id, name, number_of_seats) values ('YRQ-825-K', 'Synergistic', 180);
insert into department (id, name, number_of_seats) values ('GNF-474-G', 'circuit', 199);
insert into department (id, name, number_of_seats) values ('GTO-840-P', 'algorithm', 109);
insert into department (id, name, number_of_seats) values ('DFN-094-A', 'internet solution', 181);
insert into department (id, name, number_of_seats) values ('LAS-057-W', 'product', 172);
insert into department (id, name, number_of_seats) values ('KNO-504-F', 'even-keeled', 178);
insert into department (id, name, number_of_seats) values ('AGY-039-O', 'Switchable', 49);
insert into department (id, name, number_of_seats) values ('LYJ-651-M', 'open architecture', 183);
insert into department (id, name, number_of_seats) values ('VFX-506-I', 'project', 195);
insert into department (id, name, number_of_seats) values ('XQF-600-E', 'strategy', 130);
insert into department (id, name, number_of_seats) values ('QHO-101-M', 'paradigm', 58);
insert into department (id, name, number_of_seats) values ('OIC-124-O', 'homogeneous', 61);
insert into department (id, name, number_of_seats) values ('KLH-507-C', 'Optimized', 54);
insert into department (id, name, number_of_seats) values ('UTC-715-P', 'Seamless', 17);
insert into department (id, name, number_of_seats) values ('CAJ-695-W', 'customer loyalty', 48);
insert into department (id, name, number_of_seats) values ('JXE-835-Z', 'open architecture', 49);
insert into department (id, name, number_of_seats) values ('WNP-071-S', 'project', 108);
insert into department (id, name, number_of_seats) values ('BWI-314-B', 'Cloned', 170);
insert into department (id, name, number_of_seats) values ('KMC-722-X', 'challenge', 20);
insert into department (id, name, number_of_seats) values ('AFK-160-N', 'process improvement', 193);
insert into department (id, name, number_of_seats) values ('TUW-820-R', 'data-warehouse', 70);
insert into department (id, name, number_of_seats) values ('GAY-915-C', 'archive', 144);
insert into department (id, name, number_of_seats) values ('ILE-064-Q', 'benchmark', 45);
insert into department (id, name, number_of_seats) values ('YBG-089-Y', 'Customer-focused', 54);
insert into department (id, name, number_of_seats) values ('PDN-700-B', 'migration', 72);
insert into department (id, name, number_of_seats) values ('MLB-451-C', 'functionalities', 30);
insert into department (id, name, number_of_seats) values ('KQG-230-M', 'definition', 40);
insert into department (id, name, number_of_seats) values ('LUQ-431-X', 'zero defect', 102);
insert into department (id, name, number_of_seats) values ('RXA-236-F', 'service-desk', 17);
insert into department (id, name, number_of_seats) values ('RQA-719-U', 'responsive', 37);
insert into department (id, name, number_of_seats) values ('JUB-762-V', 'migration', 120);
insert into department (id, name, number_of_seats) values ('QBC-881-T', 'fresh-thinking', 187);
insert into department (id, name, number_of_seats) values ('XJE-909-I', 'Profound', 62);
insert into department (id, name, number_of_seats) values ('SJX-790-V', 'algorithm', 167);
insert into department (id, name, number_of_seats) values ('MAO-955-K', 'array', 160);
insert into department (id, name, number_of_seats) values ('XWG-338-T', 'multi-state', 101);
insert into department (id, name, number_of_seats) values ('WJT-183-K', 'maximized', 160);
insert into department (id, name, number_of_seats) values ('RNY-318-V', 'protocol', 146);
insert into department (id, name, number_of_seats) values ('HGB-117-K', 'fresh-thinking', 166);
insert into department (id, name, number_of_seats) values ('KEU-068-W', 'Total', 134);
insert into department (id, name, number_of_seats) values ('PYX-357-H', 'moderator', 60);
insert into department (id, name, number_of_seats) values ('STB-605-L', '5th generation', 114);
insert into department (id, name, number_of_seats) values ('BZS-494-I', 'asynchronous', 52);
insert into department (id, name, number_of_seats) values ('KLM-599-W', 'bi-directional', 79);
insert into department (id, name, number_of_seats) values ('INO-147-K', '24 hour', 60);
insert into department (id, name, number_of_seats) values ('IAE-761-O', 'portal', 93);
insert into department (id, name, number_of_seats) values ('LFI-026-J', 'Extended', 84);
insert into department (id, name, number_of_seats) values ('YVL-915-H', 'contingency', 190);
insert into department (id, name, number_of_seats) values ('UPY-832-K', 'Fundamental', 24);
insert into department (id, name, number_of_seats) values ('XYT-845-F', 'Self-enabling', 181);
insert into department (id, name, number_of_seats) values ('YXB-960-W', 'Customizable', 118);
insert into department (id, name, number_of_seats) values ('EMP-919-Q', 'eco-centric', 19);
insert into department (id, name, number_of_seats) values ('RIN-477-K', 'superstructure', 43);
insert into department (id, name, number_of_seats) values ('UFW-381-P', '24/7', 77);
insert into department (id, name, number_of_seats) values ('UFJ-443-M', 'zero administration', 60);
insert into department (id, name, number_of_seats) values ('AUX-604-M', 'architecture', 167);
insert into department (id, name, number_of_seats) values ('QCB-844-O', 'Synergistic', 61);
insert into department (id, name, number_of_seats) values ('OIB-796-I', 'Switchable', 43);
insert into department (id, name, number_of_seats) values ('JBL-510-M', 'Seamless', 41);
insert into department (id, name, number_of_seats) values ('BIZ-913-B', 'Automated', 79);
insert into department (id, name, number_of_seats) values ('ELY-611-F', 'core', 82);
insert into department (id, name, number_of_seats) values ('YPT-116-V', 'interactive', 157);
insert into department (id, name, number_of_seats) values ('LMP-878-V', 'neural-net', 79);
insert into department (id, name, number_of_seats) values ('XHE-571-K', 'groupware', 60);
insert into department (id, name, number_of_seats) values ('HYO-265-F', 'matrices', 14);
insert into department (id, name, number_of_seats) values ('ZSR-703-Z', 'Triple-buffered', 44);
insert into department (id, name, number_of_seats) values ('PXF-577-P', 'discrete', 188);
insert into department (id, name, number_of_seats) values ('ZLI-946-L', 'multi-state', 150);
insert into department (id, name, number_of_seats) values ('WSO-071-H', 'impactful', 69);
insert into department (id, name, number_of_seats) values ('ZUK-833-A', 'Focused', 66);
insert into department (id, name, number_of_seats) values ('ELH-442-F', 'synergy', 40);
insert into department (id, name, number_of_seats) values ('DRW-500-N', 'process improvement', 42);
insert into department (id, name, number_of_seats) values ('MAP-454-P', 'matrices', 170);
insert into department (id, name, number_of_seats) values ('IRU-488-J', 'upward-trending', 72);
insert into department (id, name, number_of_seats) values ('WPQ-581-Z', 'database', 151);
insert into department (id, name, number_of_seats) values ('HGJ-652-T', 'monitoring', 124);
insert into department (id, name, number_of_seats) values ('USC-882-Q', 'Decentralized', 128);
insert into department (id, name, number_of_seats) values ('AGX-818-D', 'instruction set', 47);
insert into department (id, name, number_of_seats) values ('FMT-579-L', 'database', 147);
insert into department (id, name, number_of_seats) values ('WNQ-240-S', 'help-desk', 83);
insert into department (id, name, number_of_seats) values ('ZTQ-821-H', 'challenge', 41);
insert into department (id, name, number_of_seats) values ('VCH-603-O', 'Multi-tiered', 155);
insert into department (id, name, number_of_seats) values ('PWM-031-J', 'time-frame', 180);
insert into department (id, name, number_of_seats) values ('ZOB-118-A', 'product', 116);
insert into department (id, name, number_of_seats) values ('CZJ-991-Q', 'motivating', 20);
insert into department (id, name, number_of_seats) values ('UCL-189-Y', 'logistical', 58);
insert into department (id, name, number_of_seats) values ('ECW-938-D', 'radical', 161);
insert into department (id, name, number_of_seats) values ('PNT-679-W', 'Self-enabling', 80);
insert into department (id, name, number_of_seats) values ('KEM-127-R', 'Reverse-engineered', 176);
insert into department (id, name, number_of_seats) values ('WGT-527-E', 'Diverse', 200);
insert into department (id, name, number_of_seats) values ('SRO-848-O', 'dedicated', 166);
insert into department (id, name, number_of_seats) values ('PTK-581-J', 'Virtual', 50);
insert into department (id, name, number_of_seats) values ('TWK-121-Z', 'open system', 81);
insert into department (id, name, number_of_seats) values ('YZC-513-V', 'Ameliorated', 149);
insert into department (id, name, number_of_seats) values ('ZHK-829-G', 'Right-sized', 185);
insert into department (id, name, number_of_seats) values ('DLE-869-J', 'even-keeled', 156);
insert into department (id, name, number_of_seats) values ('DUS-495-X', 'intermediate', 16);
insert into department (id, name, number_of_seats) values ('KGB-510-F', 'coherent', 112);
insert into department (id, name, number_of_seats) values ('DXA-991-D', '24 hour', 153);
insert into department (id, name, number_of_seats) values ('BCA-734-Q', 'middleware', 46);
insert into department (id, name, number_of_seats) values ('QKN-149-M', 'tangible', 188);
insert into department (id, name, number_of_seats) values ('GHW-155-E', 'Optional', 80);
insert into department (id, name, number_of_seats) values ('NLO-153-F', 'open system', 92);
insert into department (id, name, number_of_seats) values ('OLS-675-V', 'Cross-platform', 81);
insert into department (id, name, number_of_seats) values ('KBA-617-V', 'tangible', 178);
insert into department (id, name, number_of_seats) values ('PDR-860-L', 'needs-based', 37);
insert into department (id, name, number_of_seats) values ('IAU-509-H', 'well-modulated', 84);
insert into department (id, name, number_of_seats) values ('VYL-003-R', 'Implemented', 135);
insert into department (id, name, number_of_seats) values ('ZIV-712-G', 'Re-engineered', 33);
insert into department (id, name, number_of_seats) values ('WBI-016-G', 'conglomeration', 94);
insert into department (id, name, number_of_seats) values ('KVR-301-B', 'concept', 101);
insert into department (id, name, number_of_seats) values ('IZN-491-B', 'Programmable', 175);
insert into department (id, name, number_of_seats) values ('TZG-399-K', 'toolset', 15);
insert into department (id, name, number_of_seats) values ('MRV-321-V', 'well-modulated', 76);
insert into department (id, name, number_of_seats) values ('OSD-838-W', 'Distributed', 170);
insert into department (id, name, number_of_seats) values ('NBD-797-G', 'Optional', 16);
insert into department (id, name, number_of_seats) values ('BUC-892-N', 'open system', 17);
insert into department (id, name, number_of_seats) values ('SML-607-Y', 'Cloned', 82);
insert into department (id, name, number_of_seats) values ('LEW-165-E', 'instruction set', 177);
insert into department (id, name, number_of_seats) values ('AZJ-893-M', 'Multi-layered', 116);
insert into department (id, name, number_of_seats) values ('XYT-491-F', 'client-server', 27);
insert into department (id, name, number_of_seats) values ('NQX-867-E', '3rd generation', 136);
insert into department (id, name, number_of_seats) values ('SLH-214-U', 'forecast', 137);
insert into department (id, name, number_of_seats) values ('KDZ-066-S', 'methodical', 60);
insert into department (id, name, number_of_seats) values ('FBU-668-R', 'background', 154);
insert into department (id, name, number_of_seats) values ('MPU-394-U', 'Persevering', 120);
insert into department (id, name, number_of_seats) values ('ULT-891-L', 'didactic', 171);
insert into department (id, name, number_of_seats) values ('KLT-896-I', 'asymmetric', 191);
insert into department (id, name, number_of_seats) values ('AJG-287-N', 'fault-tolerant', 126);
insert into department (id, name, number_of_seats) values ('DEC-679-D', 'encompassing', 188);
insert into department (id, name, number_of_seats) values ('MVO-840-V', 'neural-net', 28);
insert into department (id, name, number_of_seats) values ('SDE-052-Q', 'asymmetric', 154);
insert into department (id, name, number_of_seats) values ('LJF-723-U', 'User-friendly', 38);
insert into department (id, name, number_of_seats) values ('LQA-056-S', 'optimizing', 197);
insert into department (id, name, number_of_seats) values ('WQL-185-A', 'solution-oriented', 14);
insert into department (id, name, number_of_seats) values ('INY-903-X', 'Integrated', 15);
insert into department (id, name, number_of_seats) values ('BUX-386-J', 'secondary', 189);
insert into department (id, name, number_of_seats) values ('JSN-382-N', 'Up-sized', 108);
insert into department (id, name, number_of_seats) values ('CVJ-759-D', 'knowledge base', 158);
insert into department (id, name, number_of_seats) values ('GOK-190-I', 'Phased', 86);
insert into department (id, name, number_of_seats) values ('DYP-689-J', 'architecture', 158);
insert into department (id, name, number_of_seats) values ('EXS-918-S', 'asymmetric', 187);
insert into department (id, name, number_of_seats) values ('AZJ-964-W', 'application', 113);
insert into department (id, name, number_of_seats) values ('VHP-690-L', 'human-resource', 40);
insert into department (id, name, number_of_seats) values ('JHV-480-M', 'database', 149);
insert into department (id, name, number_of_seats) values ('CJP-473-Y', 'executive', 32);
insert into department (id, name, number_of_seats) values ('BAM-594-Z', 'Grass-roots', 104);
insert into department (id, name, number_of_seats) values ('WSG-742-Y', 'solution-oriented', 29);
insert into department (id, name, number_of_seats) values ('QFB-619-K', 'homogeneous', 171);
insert into department (id, name, number_of_seats) values ('HDO-957-B', 'reciprocal', 41);
insert into department (id, name, number_of_seats) values ('WKN-841-B', 'portal', 79);
insert into department (id, name, number_of_seats) values ('NEI-417-H', 'Centralized', 168);
insert into department (id, name, number_of_seats) values ('SHL-153-A', 'Extended', 35);
insert into department (id, name, number_of_seats) values ('VLE-643-M', 'exuding', 114);
insert into department (id, name, number_of_seats) values ('ZXL-233-I', 'incremental', 47);
insert into department (id, name, number_of_seats) values ('SAD-904-T', 'matrices', 114);
insert into department (id, name, number_of_seats) values ('NTL-830-K', 'Integrated', 68);
insert into department (id, name, number_of_seats) values ('RZB-608-A', 'background', 138);
insert into department (id, name, number_of_seats) values ('IAC-731-O', 'Virtual', 75);
insert into department (id, name, number_of_seats) values ('RIH-985-G', 'client-driven', 45);
insert into department (id, name, number_of_seats) values ('SZR-897-X', 'strategy', 61);
insert into department (id, name, number_of_seats) values ('BDP-613-S', 'optimizing', 161);
insert into department (id, name, number_of_seats) values ('GZK-467-M', 'static', 30);
insert into department (id, name, number_of_seats) values ('QVR-537-C', 'exuding', 54);
insert into department (id, name, number_of_seats) values ('DEG-549-L', 'value-added', 198);
insert into department (id, name, number_of_seats) values ('FMI-039-R', 'needs-based', 23);
insert into department (id, name, number_of_seats) values ('EYK-236-J', 'standardization', 131);
insert into department (id, name, number_of_seats) values ('UFE-544-F', 'hierarchy', 12);
insert into department (id, name, number_of_seats) values ('JPS-919-J', 'Progressive', 106);
insert into department (id, name, number_of_seats) values ('COI-069-O', 'Compatible', 155);
insert into department (id, name, number_of_seats) values ('MGH-005-Q', 'global', 102);
insert into department (id, name, number_of_seats) values ('ONH-354-R', 'responsive', 140);
insert into department (id, name, number_of_seats) values ('HDX-920-D', 'neutral', 60);
insert into department (id, name, number_of_seats) values ('YWA-426-Q', 'secondary', 136);
insert into department (id, name, number_of_seats) values ('DPT-726-W', 'Profit-focused', 163);
insert into department (id, name, number_of_seats) values ('EFJ-001-X', 'Cross-platform', 116);
insert into department (id, name, number_of_seats) values ('MVO-079-I', 'forecast', 157);
insert into department (id, name, number_of_seats) values ('JQT-303-V', 'alliance', 143);
insert into department (id, name, number_of_seats) values ('CNW-193-O', 'Configurable', 170);
insert into department (id, name, number_of_seats) values ('IVA-710-Z', 'coherent', 185);
insert into department (id, name, number_of_seats) values ('HTW-615-A', 'empowering', 40);
insert into department (id, name, number_of_seats) values ('PEH-992-G', 'pricing structure', 175);
insert into department (id, name, number_of_seats) values ('EDF-249-C', 'logistical', 180);
insert into department (id, name, number_of_seats) values ('CTZ-669-X', 'concept', 66);
insert into department (id, name, number_of_seats) values ('TLC-542-D', 'firmware', 87);
insert into department (id, name, number_of_seats) values ('UKX-496-C', 'Mandatory', 45);
insert into department (id, name, number_of_seats) values ('FHA-391-G', 'focus group', 141);
insert into department (id, name, number_of_seats) values ('ZTF-979-J', 'clear-thinking', 173);
insert into department (id, name, number_of_seats) values ('ZLI-065-N', 'Cloned', 75);
insert into department (id, name, number_of_seats) values ('DAX-096-P', 'human-resource', 32);
insert into department (id, name, number_of_seats) values ('UOL-488-U', 'emulation', 29);
insert into department (id, name, number_of_seats) values ('IQT-372-O', 'Streamlined', 29);
insert into department (id, name, number_of_seats) values ('IXM-424-S', 'Triple-buffered', 106);
insert into department (id, name, number_of_seats) values ('BHV-216-H', 'Extended', 11);
insert into department (id, name, number_of_seats) values ('YAC-578-W', 'bottom-line', 73);
insert into department (id, name, number_of_seats) values ('JUF-981-E', 'implementation', 151);
insert into department (id, name, number_of_seats) values ('CKQ-825-Z', 'logistical', 188);
insert into department (id, name, number_of_seats) values ('OIX-064-E', 'framework', 14);
insert into department (id, name, number_of_seats) values ('EGP-249-M', 'Function-based', 193);
insert into department (id, name, number_of_seats) values ('JOU-483-V', 'dedicated', 166);
insert into department (id, name, number_of_seats) values ('DWJ-223-C', 'Quality-focused', 31);
insert into department (id, name, number_of_seats) values ('CLU-858-E', 'ability', 14);
insert into department (id, name, number_of_seats) values ('MLI-587-F', 'complexity', 144);
insert into department (id, name, number_of_seats) values ('AXB-011-R', 'Exclusive', 49);
insert into department (id, name, number_of_seats) values ('OWR-989-Q', 'focus group', 66);
insert into department (id, name, number_of_seats) values ('WRA-494-M', 'Digitized', 18);
insert into department (id, name, number_of_seats) values ('TVZ-205-B', 'Optimized', 149);
insert into department (id, name, number_of_seats) values ('VXL-703-S', 'synergy', 82);
insert into department (id, name, number_of_seats) values ('KCZ-070-D', 'asynchronous', 60);
insert into department (id, name, number_of_seats) values ('MLC-651-V', 'hardware', 42);
insert into department (id, name, number_of_seats) values ('JTI-213-V', 'Proactive', 158);
insert into department (id, name, number_of_seats) values ('JHX-557-Q', 'Optimized', 39);
insert into department (id, name, number_of_seats) values ('QDH-009-S', 'heuristic', 189);
insert into department (id, name, number_of_seats) values ('ETO-439-M', 'moderator', 194);
insert into department (id, name, number_of_seats) values ('QYM-424-S', 'tertiary', 129);
insert into department (id, name, number_of_seats) values ('XQM-974-Z', 'attitude', 14);
insert into department (id, name, number_of_seats) values ('FQZ-233-F', 'secondary', 56);
insert into department (id, name, number_of_seats) values ('ZYG-376-J', 'tangible', 86);
insert into department (id, name, number_of_seats) values ('XOZ-113-D', 'neutral', 35);
insert into department (id, name, number_of_seats) values ('MCL-509-Z', 'Integrated', 173);
insert into department (id, name, number_of_seats) values ('BHN-967-Z', 'full-range', 178);
insert into department (id, name, number_of_seats) values ('ZJF-592-G', 'Total', 180);
insert into department (id, name, number_of_seats) values ('RTE-086-L', 'service-desk', 105);
insert into department (id, name, number_of_seats) values ('UMY-942-K', 'Optional', 192);
insert into department (id, name, number_of_seats) values ('SGW-247-Y', 'Organized', 176);
insert into department (id, name, number_of_seats) values ('KPV-083-O', 'Upgradable', 38);
insert into department (id, name, number_of_seats) values ('HAW-722-Q', 'responsive', 157);
insert into department (id, name, number_of_seats) values ('CKA-211-R', 'Programmable', 98);
insert into department (id, name, number_of_seats) values ('RCM-778-T', 'Visionary', 133);
insert into department (id, name, number_of_seats) values ('YGR-320-B', 'benchmark', 53);
insert into department (id, name, number_of_seats) values ('QOZ-550-G', 'product', 68);
insert into department (id, name, number_of_seats) values ('ODK-707-T', 'Triple-buffered', 162);
insert into department (id, name, number_of_seats) values ('ZLQ-017-F', 'Decentralized', 159);
insert into department (id, name, number_of_seats) values ('MGE-798-V', 'zero defect', 46);
insert into department (id, name, number_of_seats) values ('NXQ-994-O', 'Future-proofed', 183);
insert into department (id, name, number_of_seats) values ('NOS-198-L', 'context-sensitive', 173);
insert into department (id, name, number_of_seats) values ('SFN-999-N', 'Intuitive', 140);
insert into department (id, name, number_of_seats) values ('HQS-490-B', 'success', 96);
insert into department (id, name, number_of_seats) values ('LSU-718-A', 'bandwidth-monitored', 156);
insert into department (id, name, number_of_seats) values ('LQS-830-L', 'radical', 148);
insert into department (id, name, number_of_seats) values ('IUJ-602-M', 'value-added', 185);
insert into department (id, name, number_of_seats) values ('RQX-367-F', 'zero defect', 95);
insert into department (id, name, number_of_seats) values ('TNA-917-Z', 'Polarised', 198);
insert into department (id, name, number_of_seats) values ('XEM-564-Z', 'zero defect', 85);
insert into department (id, name, number_of_seats) values ('RMP-641-K', 'protocol', 65);
insert into department (id, name, number_of_seats) values ('CQZ-967-H', 'migration', 135);
insert into department (id, name, number_of_seats) values ('UBG-195-Y', 'complexity', 137);
insert into department (id, name, number_of_seats) values ('BCG-605-W', 'Integrated', 14);
insert into department (id, name, number_of_seats) values ('HQI-901-H', 'encoding', 174);
insert into department (id, name, number_of_seats) values ('VZQ-426-C', 'bifurcated', 165);
insert into department (id, name, number_of_seats) values ('TLI-243-V', 'intranet', 107);
insert into department (id, name, number_of_seats) values ('TQW-973-L', 'Enhanced', 65);
insert into department (id, name, number_of_seats) values ('DYI-202-Y', 'artificial intelligence', 179);
insert into department (id, name, number_of_seats) values ('FNJ-923-J', 'projection', 127);
insert into department (id, name, number_of_seats) values ('XTM-914-L', 'Graphic Interface', 144);
insert into department (id, name, number_of_seats) values ('VBZ-626-N', 'client-driven', 154);
insert into department (id, name, number_of_seats) values ('ZKJ-271-T', 'multimedia', 135);
insert into department (id, name, number_of_seats) values ('KGL-450-M', 'Advanced', 85);
insert into department (id, name, number_of_seats) values ('FGM-150-W', 'tertiary', 105);
insert into department (id, name, number_of_seats) values ('PEB-181-Z', 'human-resource', 65);
insert into department (id, name, number_of_seats) values ('AXY-937-F', 'Multi-lateral', 140);
insert into department (id, name, number_of_seats) values ('WPN-169-W', 'multimedia', 37);
insert into department (id, name, number_of_seats) values ('JPV-714-M', 'application', 110);
insert into department (id, name, number_of_seats) values ('FXY-558-F', 'Inverse', 132);
insert into department (id, name, number_of_seats) values ('NEW-383-Q', 'Fundamental', 134);
insert into department (id, name, number_of_seats) values ('YPX-218-S', 'Progressive', 179);
insert into department (id, name, number_of_seats) values ('WOG-002-K', 'ability', 150);
insert into department (id, name, number_of_seats) values ('ARG-939-Z', 'fresh-thinking', 70);
insert into department (id, name, number_of_seats) values ('XDN-194-B', 'logistical', 95);
insert into department (id, name, number_of_seats) values ('PZN-370-E', 'Triple-buffered', 87);
insert into department (id, name, number_of_seats) values ('URS-126-R', 'dynamic', 85);
insert into department (id, name, number_of_seats) values ('MCE-038-C', 'disintermediate', 67);
insert into department (id, name, number_of_seats) values ('TKF-508-O', 'exuding', 17);
insert into department (id, name, number_of_seats) values ('UED-414-Z', 'circuit', 87);
insert into department (id, name, number_of_seats) values ('TIA-165-T', 'real-time', 197);
insert into department (id, name, number_of_seats) values ('BUH-100-V', 'Mandatory', 111);
insert into department (id, name, number_of_seats) values ('FOC-680-T', 'Seamless', 171);
insert into department (id, name, number_of_seats) values ('BKI-749-B', 'cohesive', 20);
insert into department (id, name, number_of_seats) values ('BVC-704-B', '24/7', 92);
insert into department (id, name, number_of_seats) values ('JAE-402-F', 'tangible', 148);
insert into department (id, name, number_of_seats) values ('PFU-785-F', 'Assimilated', 20);
insert into department (id, name, number_of_seats) values ('OBJ-216-Z', 'Secured', 86);
insert into department (id, name, number_of_seats) values ('MGD-315-I', 'software', 183);
insert into department (id, name, number_of_seats) values ('UNG-419-P', 'Vision-oriented', 161);
insert into department (id, name, number_of_seats) values ('PCQ-865-Z', 'Phased', 45);
insert into department (id, name, number_of_seats) values ('ZBL-391-P', 'system engine', 108);
insert into department (id, name, number_of_seats) values ('WMF-332-A', 'budgetary management', 44);
insert into department (id, name, number_of_seats) values ('MIN-487-W', '24 hour', 41);
insert into department (id, name, number_of_seats) values ('BTG-670-F', 'Visionary', 85);
insert into department (id, name, number_of_seats) values ('RSU-657-P', 'project', 91);
insert into department (id, name, number_of_seats) values ('JYN-580-Z', 'Re-engineered', 34);
insert into department (id, name, number_of_seats) values ('BGV-564-B', 'regional', 72);
insert into department (id, name, number_of_seats) values ('ILK-407-L', 'Face to face', 94);
insert into department (id, name, number_of_seats) values ('OIZ-524-X', 'Persevering', 116);
insert into department (id, name, number_of_seats) values ('YMO-288-R', 'solution', 179);
insert into department (id, name, number_of_seats) values ('KJI-111-N', 'Monitored', 144);
insert into department (id, name, number_of_seats) values ('DAU-309-R', 'capability', 67);
insert into department (id, name, number_of_seats) values ('SAV-994-S', 'systematic', 78);
insert into department (id, name, number_of_seats) values ('ZFB-878-D', 'Balanced', 168);
insert into department (id, name, number_of_seats) values ('GZW-150-G', 'encoding', 89);
insert into department (id, name, number_of_seats) values ('OIW-836-D', 'responsive', 28);
insert into department (id, name, number_of_seats) values ('PIS-324-Y', 'Profit-focused', 112);
insert into department (id, name, number_of_seats) values ('ULZ-731-R', 'holistic', 152);
insert into department (id, name, number_of_seats) values ('NWG-934-Q', 'flexibility', 95);
insert into department (id, name, number_of_seats) values ('TKP-802-H', 'responsive', 61);
insert into department (id, name, number_of_seats) values ('AXN-571-V', 'Up-sized', 91);
insert into department (id, name, number_of_seats) values ('XKB-325-U', 'system-worthy', 123);
insert into department (id, name, number_of_seats) values ('UCV-607-U', 'context-sensitive', 197);
insert into department (id, name, number_of_seats) values ('HJY-708-T', 'Object-based', 55);
insert into department (id, name, number_of_seats) values ('LHG-542-X', 'object-oriented', 168);
insert into department (id, name, number_of_seats) values ('YHB-877-J', 'Intuitive', 29);
insert into department (id, name, number_of_seats) values ('UKD-343-N', 'composite', 166);
insert into department (id, name, number_of_seats) values ('GTA-307-N', 'Devolved', 127);
insert into department (id, name, number_of_seats) values ('LJG-389-S', 'Focused', 49);
insert into department (id, name, number_of_seats) values ('TMF-869-H', 'extranet', 140);
insert into department (id, name, number_of_seats) values ('AYK-897-K', 'object-oriented', 190);
insert into department (id, name, number_of_seats) values ('BMI-496-F', 'methodical', 39);
insert into department (id, name, number_of_seats) values ('SRK-914-Z', 'Customizable', 137);
insert into department (id, name, number_of_seats) values ('PLO-064-Z', 'Universal', 143);
insert into department (id, name, number_of_seats) values ('XWU-454-Q', 'client-server', 125);
insert into department (id, name, number_of_seats) values ('KOC-743-D', 'model', 79);
insert into department (id, name, number_of_seats) values ('VSM-997-L', 'toolset', 165);
insert into department (id, name, number_of_seats) values ('RGI-405-Z', 'bandwidth-monitored', 168);
insert into department (id, name, number_of_seats) values ('UBS-217-Q', 'Monitored', 197);
insert into department (id, name, number_of_seats) values ('RKG-276-Y', 'Multi-tiered', 108);
insert into department (id, name, number_of_seats) values ('TRN-435-W', '5th generation', 194);
insert into department (id, name, number_of_seats) values ('KMD-270-R', 'workforce', 127);
insert into department (id, name, number_of_seats) values ('LGR-493-C', 'pricing structure', 53);
insert into department (id, name, number_of_seats) values ('PBS-973-C', 'zero administration', 16);
insert into department (id, name, number_of_seats) values ('ZKU-833-D', 'Customizable', 42);
insert into department (id, name, number_of_seats) values ('ENO-685-S', 'Persevering', 77);
insert into department (id, name, number_of_seats) values ('FOS-679-K', 'Networked', 193);
insert into department (id, name, number_of_seats) values ('NQT-716-J', 'frame', 103);
insert into department (id, name, number_of_seats) values ('CJN-618-O', 'access', 102);
insert into department (id, name, number_of_seats) values ('ABJ-260-C', 'bifurcated', 190);
insert into department (id, name, number_of_seats) values ('ZMV-793-A', 'logistical', 100);
insert into department (id, name, number_of_seats) values ('SVI-914-A', 'Universal', 102);
insert into department (id, name, number_of_seats) values ('QUR-948-K', 'regional', 168);
insert into department (id, name, number_of_seats) values ('JDT-565-D', 'local', 167);
insert into department (id, name, number_of_seats) values ('IJM-155-U', 'challenge', 194);
insert into department (id, name, number_of_seats) values ('QKL-949-Z', 'system engine', 149);
insert into department (id, name, number_of_seats) values ('RTP-896-U', 'capacity', 53);
insert into department (id, name, number_of_seats) values ('UKW-410-R', '24 hour', 34);
insert into department (id, name, number_of_seats) values ('LVW-217-V', 'Persevering', 145);
insert into department (id, name, number_of_seats) values ('SUZ-946-G', 'Fully-configurable', 84);
insert into department (id, name, number_of_seats) values ('WJP-053-Q', 'superstructure', 151);
insert into department (id, name, number_of_seats) values ('PSN-334-B', 'full-range', 176);
insert into department (id, name, number_of_seats) values ('MSK-658-C', 'Graphic Interface', 15);
insert into department (id, name, number_of_seats) values ('CRB-855-I', 'Synergistic', 184);
insert into department (id, name, number_of_seats) values ('ASE-011-O', 'Multi-lateral', 37);
insert into department (id, name, number_of_seats) values ('EQA-691-I', 'multi-tasking', 95);
insert into department (id, name, number_of_seats) values ('CZO-228-S', 'system-worthy', 190);
insert into department (id, name, number_of_seats) values ('KEW-782-V', 'Configurable', 47);
insert into department (id, name, number_of_seats) values ('JUN-940-C', '24/7', 127);
insert into department (id, name, number_of_seats) values ('RPQ-160-T', 'approach', 74);
insert into department (id, name, number_of_seats) values ('IPQ-474-I', 'Fully-configurable', 94);
insert into department (id, name, number_of_seats) values ('DUQ-553-G', 'Versatile', 55);
insert into department (id, name, number_of_seats) values ('KNB-122-G', 'intranet', 164);
insert into department (id, name, number_of_seats) values ('SPX-435-Q', 'success', 38);
insert into department (id, name, number_of_seats) values ('ZTN-593-A', 'Adaptive', 171);
insert into department (id, name, number_of_seats) values ('BSJ-504-A', 'synergy', 175);
insert into department (id, name, number_of_seats) values ('BRT-639-Q', 'contextually-based', 48);
insert into department (id, name, number_of_seats) values ('DYR-568-X', 'protocol', 29);
insert into department (id, name, number_of_seats) values ('TBK-382-Z', 'Configurable', 122);
insert into department (id, name, number_of_seats) values ('LBW-268-G', 'Multi-tiered', 18);
insert into department (id, name, number_of_seats) values ('EPB-226-F', 'Reduced', 158);
insert into department (id, name, number_of_seats) values ('BWD-583-R', 'high-level', 95);
insert into department (id, name, number_of_seats) values ('TXD-513-I', 'circuit', 56);
insert into department (id, name, number_of_seats) values ('UBD-833-J', 'array', 60);
insert into department (id, name, number_of_seats) values ('GLX-086-B', 'parallelism', 30);
insert into department (id, name, number_of_seats) values ('YOR-478-L', 'Ameliorated', 189);
insert into department (id, name, number_of_seats) values ('CGN-766-V', 'asynchronous', 86);
insert into department (id, name, number_of_seats) values ('AFQ-978-T', 'Robust', 86);
insert into department (id, name, number_of_seats) values ('HRM-166-S', 'non-volatile', 128);
insert into department (id, name, number_of_seats) values ('RSP-846-Q', 'Synchronised', 47);
insert into department (id, name, number_of_seats) values ('WHQ-006-C', 'tertiary', 51);
insert into department (id, name, number_of_seats) values ('PVN-736-E', 'Advanced', 164);
insert into department (id, name, number_of_seats) values ('ZUQ-746-L', 'Re-contextualized', 81);
insert into department (id, name, number_of_seats) values ('WKD-784-J', 'Intuitive', 145);
insert into department (id, name, number_of_seats) values ('CQR-151-M', 'Automated', 200);
insert into department (id, name, number_of_seats) values ('LZO-103-R', 'Re-contextualized', 159);
insert into department (id, name, number_of_seats) values ('GMB-455-O', 'matrix', 87);
insert into department (id, name, number_of_seats) values ('KMD-604-F', 'throughput', 12);
insert into department (id, name, number_of_seats) values ('QKT-039-L', 'stable', 66);
insert into department (id, name, number_of_seats) values ('WCZ-501-J', 'Face to face', 187);
insert into department (id, name, number_of_seats) values ('HXY-245-R', 'hub', 80);
insert into department (id, name, number_of_seats) values ('THW-285-M', 'Horizontal', 163);
insert into department (id, name, number_of_seats) values ('SIK-293-U', 'hub', 175);
insert into department (id, name, number_of_seats) values ('SWB-595-I', 'Up-sized', 121);
insert into department (id, name, number_of_seats) values ('YSR-115-K', 'Configurable', 184);
insert into department (id, name, number_of_seats) values ('GVU-731-K', 'incremental', 15);
insert into department (id, name, number_of_seats) values ('TJL-587-M', 'projection', 73);
insert into department (id, name, number_of_seats) values ('LXB-666-S', 'support', 186);
insert into department (id, name, number_of_seats) values ('FDV-363-H', 'fault-tolerant', 131);
insert into department (id, name, number_of_seats) values ('AYN-423-H', 'real-time', 82);
insert into department (id, name, number_of_seats) values ('BTL-396-T', 'neutral', 156);
insert into department (id, name, number_of_seats) values ('BDM-295-E', 'zero defect', 38);
insert into department (id, name, number_of_seats) values ('IBR-213-E', 'framework', 111);
insert into department (id, name, number_of_seats) values ('CAF-140-K', 'empowering', 156);
insert into department (id, name, number_of_seats) values ('FPG-332-M', 'interface', 78);
insert into department (id, name, number_of_seats) values ('PON-625-K', 'Virtual', 177);
insert into department (id, name, number_of_seats) values ('CPO-427-D', 'access', 52);
insert into department (id, name, number_of_seats) values ('TSF-026-D', 'context-sensitive', 146);
insert into department (id, name, number_of_seats) values ('ZEY-892-S', 'didactic', 192);
insert into department (id, name, number_of_seats) values ('AGV-027-Q', 'Horizontal', 170);
insert into department (id, name, number_of_seats) values ('AMT-801-J', 'modular', 37);
insert into department (id, name, number_of_seats) values ('RJQ-520-R', 'multimedia', 150);
insert into department (id, name, number_of_seats) values ('PDM-759-S', 'pricing structure', 68);
insert into department (id, name, number_of_seats) values ('OTR-600-B', 'Re-engineered', 18);
insert into department (id, name, number_of_seats) values ('ADM-679-L', 'internet solution', 152);
insert into department (id, name, number_of_seats) values ('PZY-659-U', 'time-frame', 63);
insert into department (id, name, number_of_seats) values ('LJM-024-Y', 'pricing structure', 68);
insert into department (id, name, number_of_seats) values ('EPC-141-D', 'archive', 165);
insert into department (id, name, number_of_seats) values ('AFV-395-X', 'initiative', 93);
insert into department (id, name, number_of_seats) values ('KSR-551-L', 'interactive', 51);
insert into department (id, name, number_of_seats) values ('MKQ-238-O', 'Customizable', 131);
insert into department (id, name, number_of_seats) values ('BMO-070-S', '24/7', 100);
insert into department (id, name, number_of_seats) values ('CTR-095-V', 'neutral', 193);
insert into department (id, name, number_of_seats) values ('NEX-099-F', 'multi-state', 64);
insert into department (id, name, number_of_seats) values ('INX-255-F', 'real-time', 72);
insert into department (id, name, number_of_seats) values ('VEM-545-Y', 'collaboration', 128);
insert into department (id, name, number_of_seats) values ('AUT-162-W', 'definition', 82);
insert into department (id, name, number_of_seats) values ('GRN-425-F', 'task-force', 96);
insert into department (id, name, number_of_seats) values ('KBT-162-E', 'Customizable', 51);
insert into department (id, name, number_of_seats) values ('QRP-524-W', 'Compatible', 83);
insert into department (id, name, number_of_seats) values ('TMK-157-W', 'Front-line', 143);
insert into department (id, name, number_of_seats) values ('IWX-125-P', 'productivity', 17);
insert into department (id, name, number_of_seats) values ('HWN-330-Z', 'non-volatile', 75);
insert into department (id, name, number_of_seats) values ('NWD-694-V', 'analyzer', 177);
insert into department (id, name, number_of_seats) values ('THC-683-P', 'secondary', 79);
insert into department (id, name, number_of_seats) values ('FXU-455-M', 'actuating', 74);
insert into department (id, name, number_of_seats) values ('EVT-338-G', 'regional', 158);
insert into department (id, name, number_of_seats) values ('VPG-635-L', 'De-engineered', 129);
insert into department (id, name, number_of_seats) values ('VKA-960-N', 'middleware', 96);
insert into department (id, name, number_of_seats) values ('WBK-988-V', 'heuristic', 61);
insert into department (id, name, number_of_seats) values ('LGZ-333-L', 'Reactive', 59);
insert into department (id, name, number_of_seats) values ('OFS-694-O', 'contextually-based', 157);
insert into department (id, name, number_of_seats) values ('KCV-018-X', 'systematic', 153);
insert into department (id, name, number_of_seats) values ('SJG-304-P', 'Self-enabling', 99);
insert into department (id, name, number_of_seats) values ('JFI-451-N', 'service-desk', 175);
insert into department (id, name, number_of_seats) values ('QYG-579-U', 'focus group', 29);
insert into department (id, name, number_of_seats) values ('SEA-646-P', 'neural-net', 83);
insert into department (id, name, number_of_seats) values ('VFZ-963-Q', 'cohesive', 155);
insert into department (id, name, number_of_seats) values ('ICR-610-R', 'neural-net', 77);
insert into department (id, name, number_of_seats) values ('NSA-882-W', 'website', 160);
insert into department (id, name, number_of_seats) values ('HOR-867-G', 'Organized', 142);
insert into department (id, name, number_of_seats) values ('VMN-047-W', 'success', 177);
insert into department (id, name, number_of_seats) values ('DCO-777-V', 'Programmable', 131);
insert into department (id, name, number_of_seats) values ('FAW-192-Z', 'Polarised', 66);
insert into department (id, name, number_of_seats) values ('JBE-820-W', 'installation', 121);
insert into department (id, name, number_of_seats) values ('YKV-891-X', 'Synchronised', 62);
insert into department (id, name, number_of_seats) values ('NEW-777-T', 'Object-based', 138);
insert into department (id, name, number_of_seats) values ('TUI-329-T', 'next generation', 165);
insert into department (id, name, number_of_seats) values ('AEY-919-F', 'Right-sized', 85);
insert into department (id, name, number_of_seats) values ('KGH-040-V', 'instruction set', 132);
insert into department (id, name, number_of_seats) values ('TKA-746-S', 'Profound', 113);
insert into department (id, name, number_of_seats) values ('EAN-770-Z', 'function', 176);
insert into department (id, name, number_of_seats) values ('MQA-224-H', 'next generation', 153);
insert into department (id, name, number_of_seats) values ('PBI-487-R', 'Ameliorated', 47);
insert into department (id, name, number_of_seats) values ('WEU-688-O', 'intranet', 83);
insert into department (id, name, number_of_seats) values ('RZY-256-H', 'matrices', 22);
insert into department (id, name, number_of_seats) values ('UAX-386-F', 'interactive', 125);
insert into department (id, name, number_of_seats) values ('BRL-627-W', 'standardization', 164);
insert into department (id, name, number_of_seats) values ('PVH-951-E', 'extranet', 140);
insert into department (id, name, number_of_seats) values ('AVI-917-A', 'Upgradable', 17);
insert into department (id, name, number_of_seats) values ('XMF-666-Y', 'disintermediate', 168);
insert into department (id, name, number_of_seats) values ('LWZ-099-C', 'website', 32);
insert into department (id, name, number_of_seats) values ('AVG-638-V', 'Upgradable', 111);
insert into department (id, name, number_of_seats) values ('JGC-948-E', 'Open-architected', 144);
insert into department (id, name, number_of_seats) values ('ZEO-323-X', 'holistic', 26);
insert into department (id, name, number_of_seats) values ('DJO-824-P', 'Automated', 35);
insert into department (id, name, number_of_seats) values ('YDF-112-H', 'Public-key', 120);
insert into department (id, name, number_of_seats) values ('JPW-882-P', 'Implemented', 68);
insert into department (id, name, number_of_seats) values ('YSB-153-K', 'regional', 191);
insert into department (id, name, number_of_seats) values ('FJD-703-G', 'encryption', 81);
insert into department (id, name, number_of_seats) values ('SMG-192-S', 'Multi-layered', 96);
insert into department (id, name, number_of_seats) values ('OAU-120-N', 'Synchronised', 191);
insert into department (id, name, number_of_seats) values ('ZVQ-035-Q', 'Front-line', 182);
insert into department (id, name, number_of_seats) values ('WHX-665-K', 'bottom-line', 73);
insert into department (id, name, number_of_seats) values ('IKQ-468-R', 'global', 182);
insert into department (id, name, number_of_seats) values ('PTW-057-W', 'regional', 87);
insert into department (id, name, number_of_seats) values ('FQT-328-K', 'Optional', 139);
insert into department (id, name, number_of_seats) values ('IGD-778-L', 'utilisation', 178);
insert into department (id, name, number_of_seats) values ('ZTO-297-J', 'middleware', 73);
insert into department (id, name, number_of_seats) values ('ZCO-077-P', 'product', 132);
insert into department (id, name, number_of_seats) values ('BUA-944-W', 'foreground', 22);
insert into department (id, name, number_of_seats) values ('OQX-550-Q', 'optimizing', 141);
insert into department (id, name, number_of_seats) values ('WIO-854-S', 'challenge', 78);
insert into department (id, name, number_of_seats) values ('MOT-438-Q', 'Enhanced', 83);
insert into department (id, name, number_of_seats) values ('TAO-134-T', 'hierarchy', 146);
insert into department (id, name, number_of_seats) values ('QYF-977-D', 'focus group', 179);
insert into department (id, name, number_of_seats) values ('QWV-256-R', 'Cross-group', 81);
insert into department (id, name, number_of_seats) values ('JLH-008-V', 'Organic', 133);
insert into department (id, name, number_of_seats) values ('RFC-743-K', 'Proactive', 158);
insert into department (id, name, number_of_seats) values ('VZU-406-L', 'Multi-tiered', 60);
insert into department (id, name, number_of_seats) values ('YTQ-415-X', 'forecast', 21);
insert into department (id, name, number_of_seats) values ('PBT-396-E', 'content-based', 85);
insert into department (id, name, number_of_seats) values ('QJY-215-C', 'eco-centric', 128);
insert into department (id, name, number_of_seats) values ('GNP-312-Q', 'methodology', 57);
insert into department (id, name, number_of_seats) values ('CKP-062-V', 'Right-sized', 166);
insert into department (id, name, number_of_seats) values ('LHS-662-M', '5th generation', 69);
insert into department (id, name, number_of_seats) values ('NMH-533-U', 'parallelism', 122);
insert into department (id, name, number_of_seats) values ('EGL-811-B', 'interactive', 180);
insert into department (id, name, number_of_seats) values ('EDN-051-F', 'Graphic Interface', 150);
insert into department (id, name, number_of_seats) values ('FLC-976-X', 'Robust', 135);
insert into department (id, name, number_of_seats) values ('WXZ-120-P', 'secured line', 188);
insert into department (id, name, number_of_seats) values ('YOV-774-K', 'fresh-thinking', 100);
insert into department (id, name, number_of_seats) values ('SGO-798-U', 'Distributed', 83);
insert into department (id, name, number_of_seats) values ('PLN-488-U', 'encoding', 185);
insert into department (id, name, number_of_seats) values ('TVB-035-B', 'framework', 130);
insert into department (id, name, number_of_seats) values ('JWM-700-X', 'disintermediate', 63);
insert into department (id, name, number_of_seats) values ('YMV-323-V', 'interface', 156);
insert into department (id, name, number_of_seats) values ('VOT-724-P', 'orchestration', 84);
insert into department (id, name, number_of_seats) values ('BCP-473-P', 'encompassing', 198);
insert into department (id, name, number_of_seats) values ('XVG-056-N', 'User-centric', 21);
insert into department (id, name, number_of_seats) values ('QLK-954-J', 'De-engineered', 21);
insert into department (id, name, number_of_seats) values ('UDQ-543-Z', 'explicit', 192);
insert into department (id, name, number_of_seats) values ('GVB-360-O', 'Reactive', 135);
insert into department (id, name, number_of_seats) values ('FAR-850-F', 'didactic', 53);
insert into department (id, name, number_of_seats) values ('VBI-805-S', 'tangible', 79);
insert into department (id, name, number_of_seats) values ('BFD-741-Z', 'motivating', 127);
insert into department (id, name, number_of_seats) values ('PBV-045-A', 'interactive', 200);
insert into department (id, name, number_of_seats) values ('WKR-414-W', 'transitional', 54);
insert into department (id, name, number_of_seats) values ('XLP-016-Y', 'pricing structure', 16);
insert into department (id, name, number_of_seats) values ('CIA-540-O', 'frame', 58);
insert into department (id, name, number_of_seats) values ('BIN-625-B', 'mobile', 32);
insert into department (id, name, number_of_seats) values ('QPL-399-Q', 'Decentralized', 135);
insert into department (id, name, number_of_seats) values ('NIJ-110-B', 'open system', 176);
insert into department (id, name, number_of_seats) values ('MIX-263-Q', 'multimedia', 53);
insert into department (id, name, number_of_seats) values ('PJV-580-U', 'Function-based', 67);
insert into department (id, name, number_of_seats) values ('ORQ-246-L', 'Implemented', 23);
insert into department (id, name, number_of_seats) values ('IZE-778-R', 'Profit-focused', 163);
insert into department (id, name, number_of_seats) values ('PTB-900-I', 'Right-sized', 140);
insert into department (id, name, number_of_seats) values ('ZOM-811-I', 'paradigm', 175);
insert into department (id, name, number_of_seats) values ('KLS-110-S', 'maximized', 174);
insert into department (id, name, number_of_seats) values ('UNL-234-U', 'human-resource', 79);
insert into department (id, name, number_of_seats) values ('VIR-031-W', 'neutral', 39);
insert into department (id, name, number_of_seats) values ('GRY-147-V', 'Grass-roots', 46);
insert into department (id, name, number_of_seats) values ('JGY-167-Q', 'Virtual', 65);
insert into department (id, name, number_of_seats) values ('YEB-352-A', 'alliance', 85);
insert into department (id, name, number_of_seats) values ('QIP-252-X', 'local area network', 20);
insert into department (id, name, number_of_seats) values ('IDK-162-X', 'even-keeled', 168);
insert into department (id, name, number_of_seats) values ('ZTQ-444-Q', 'eco-centric', 197);
insert into department (id, name, number_of_seats) values ('IKM-576-X', 'Optimized', 113);
insert into department (id, name, number_of_seats) values ('VBA-806-T', 'artificial intelligence', 135);
insert into department (id, name, number_of_seats) values ('LOX-313-X', 'Seamless', 76);
insert into department (id, name, number_of_seats) values ('XGC-729-W', 'Total', 34);
insert into department (id, name, number_of_seats) values ('TON-761-A', 'Business-focused', 16);
insert into department (id, name, number_of_seats) values ('BCT-315-M', 'matrix', 126);
insert into department (id, name, number_of_seats) values ('RPC-117-N', 'neural-net', 23);
insert into department (id, name, number_of_seats) values ('DKV-080-L', 'Operative', 98);
insert into department (id, name, number_of_seats) values ('PTD-519-D', 'Expanded', 25);
insert into department (id, name, number_of_seats) values ('BFT-909-E', 'leverage', 71);
insert into department (id, name, number_of_seats) values ('DPX-150-J', 'moderator', 72);
insert into department (id, name, number_of_seats) values ('NTJ-703-T', 'portal', 169);
insert into department (id, name, number_of_seats) values ('LWO-831-C', 'Extended', 115);
insert into department (id, name, number_of_seats) values ('JSQ-722-Q', 'time-frame', 77);
insert into department (id, name, number_of_seats) values ('MCA-927-W', 'Enterprise-wide', 132);
insert into department (id, name, number_of_seats) values ('ZKI-656-M', 'process improvement', 126);
insert into department (id, name, number_of_seats) values ('RVG-579-R', 'Configurable', 65);
insert into department (id, name, number_of_seats) values ('YPL-236-N', 'support', 25);
insert into department (id, name, number_of_seats) values ('HLP-518-V', 'methodical', 10);
insert into department (id, name, number_of_seats) values ('HRT-400-R', 'tertiary', 14);
insert into department (id, name, number_of_seats) values ('VGQ-592-M', 'Assimilated', 128);
insert into department (id, name, number_of_seats) values ('SWU-199-T', 'forecast', 58);
insert into department (id, name, number_of_seats) values ('MNZ-694-Q', 'Persistent', 106);
insert into department (id, name, number_of_seats) values ('UZI-506-Z', 'regional', 21);
insert into department (id, name, number_of_seats) values ('PZV-727-M', 'framework', 27);
insert into department (id, name, number_of_seats) values ('CNH-144-U', 'bifurcated', 136);
insert into department (id, name, number_of_seats) values ('NMX-480-L', 'context-sensitive', 101);
insert into department (id, name, number_of_seats) values ('MXC-157-Y', 'hardware', 54);
insert into department (id, name, number_of_seats) values ('JAK-044-K', 'leverage', 31);
insert into department (id, name, number_of_seats) values ('WCE-858-E', 'process improvement', 84);
insert into department (id, name, number_of_seats) values ('RMX-050-A', 'hub', 58);
insert into department (id, name, number_of_seats) values ('MFX-325-E', 'infrastructure', 40);
insert into department (id, name, number_of_seats) values ('MZP-386-X', 'national', 148);
insert into department (id, name, number_of_seats) values ('JWK-250-T', 'modular', 11);
insert into department (id, name, number_of_seats) values ('ZYV-267-W', 'system engine', 65);
insert into department (id, name, number_of_seats) values ('KMA-892-K', 'object-oriented', 44);
insert into department (id, name, number_of_seats) values ('XLB-508-S', 'hub', 137);
insert into department (id, name, number_of_seats) values ('MUI-224-T', 'static', 117);
insert into department (id, name, number_of_seats) values ('SOB-065-H', 'user-facing', 63);
insert into department (id, name, number_of_seats) values ('LJZ-340-A', 'workforce', 69);
insert into department (id, name, number_of_seats) values ('WFV-584-Q', 'implementation', 75);
insert into department (id, name, number_of_seats) values ('KMO-031-Q', 'complexity', 181);